import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://localhost:3000';

export const metadata: Metadata = {
  metadataBase: new URL(baseUrl),
  title: {
    default: "PureSearch - Find Human-Written, Non-AI Generated Content",
    template: "%s | PureSearch"
  },
  description: "Discover authentic, human-written content across the web. PureSearch helps you find reliable information that is not generated by AI.",
  keywords: ["search engine", "human content", "non-ai content", "authentic content", "reliable search"],
  authors: [{ name: "PureSearch Team" }],
  creator: "PureSearch",
  publisher: "PureSearch",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: '/',
    siteName: 'PureSearch',
    title: 'PureSearch - Find Human-Written, Non-AI Generated Content',
    description: 'Discover authentic, human-written content across the web. PureSearch helps you find reliable information that is not generated by AI.',
    images: [
      {
        url: `/api/og?title=${encodeURIComponent('PureSearch')}&description=${encodeURIComponent('Find authentic, human-written content')}`,
        width: 1200,
        height: 630,
        alt: 'PureSearch - Find Human-Written Content',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'PureSearch - Find Human-Written, Non-AI Generated Content',
    description: 'Discover authentic, human-written content across the web. PureSearch helps you find reliable information that is not generated by AI.',
    images: [`/api/og?title=${encodeURIComponent('PureSearch')}&description=${encodeURIComponent('Find authentic, human-written content')}`],
    creator: '@puresearch',
  },
  icons: {
    icon: [
      {
        url: "/api/favicon",
        sizes: "192x192",
        type: "image/png",
      },
    ],
    apple: [
      {
        url: "/api/favicon",
        sizes: "180x180",
        type: "image/png",
      },
    ],
    shortcut: ["/api/favicon"],
  },
  manifest: '/site.webmanifest',
  alternates: {
    canonical: '/',
  },
  verification: {
    google: 'google-site-verification-code', // Replace with actual verification code when available
  },
  other: {
    'google-site-verification': 'google-site-verification-code', // Replace with actual verification code when available
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
